force-app/main/default/objects/Ano__c/Ano__c.object-meta.xml
<CustomObject>
    <label>Ano</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ano</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bomba__c/Bomba__c.object-meta.xml
<CustomObject>
    <label>Bomba</label>
    <nameField>
        <label>Nome de Bomba</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bombas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bomba__c/fields/Ano_de_Fabricacao__c.field-meta.xml
<CustomField>
    <fullName>Ano_de_Fabricacao__c</fullName>
    <label>Ano de Fabricacao</label>
    <referenceTo>Ano__c</referenceTo>
    <relationshipLabel>Bombas</relationshipLabel>
    <relationshipName>Bombas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bomba__c/fields/idProprietario__c.field-meta.xml
<CustomField>
    <fullName>idProprietario__c</fullName>
    <label>idProprietario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BombaTest.cls
@isTest
public class BombaTest {

    public static testmethod void TestandoBomba()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='Administrador do Sistema']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='User1@teste.com.sdygfystarf', Consultor__c = true);
        
        
        User u2 = new User(Alias = 'standt2', Email='standarduser2@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='User2@teste.com.sdygfystarf',  Consultor__c = true);
        
       insert u;
       insert u2;
        
        
        Ano__c ano = new Ano__c();
        insert ano;
        
        Bomba__c b1 = new Bomba__c(Name= 'Bomba 1', Ano_de_Fabricacao__c = ano.Id);       
   		Bomba__c b2 = new Bomba__c(Name= 'Bomba 2', Ano_de_Fabricacao__c = ano.Id);
        Bomba__c b3 = new Bomba__c(Name= 'Bomba 3', Ano_de_Fabricacao__c = ano.Id);
        Bomba__c b4 = new Bomba__c(Name= 'Bomba 4', Ano_de_Fabricacao__c = ano.Id);
        Bomba__c b5 = new Bomba__c(Name= 'Bomba 5', Ano_de_Fabricacao__c = ano.Id);
        
        
        List<Bomba__c> listBomb = new List<Bomba__c>();
    	listBomb.add(b1);
    	listBomb.add(b2);
        listBomb.add(b3);
        listBomb.add(b4);
        listBomb.add(b5);
        
        System.runAs(u)
        {
        	Test.startTest();
        insert listBomb;
       
		String aux = u2.Id;
        aux = aux.substring(0, 15);
         System.debug('u2 :' + aux);
        listBomb = [Select Id, Name From Bomba__c Where idProprietario__c = :aux];
        //System.assert(listBomb.size() < 4);
        //System.assert(listBomb.size() > 1);
        
        System.debug('U2' + ' ' + listBomb.size());
    
        String aux1 = u.Id;
        aux1 = aux1.substring(0, 15);
         System.debug(aux1);
        
        listBomb = [Select Id, Name From Bomba__c Where idProprietario__c = :aux1];
        
         System.debug('U' + ' ' + listBomb.size());
        //System.assert(listBomb.size() < 4);
        //System.assert(listBomb.size() > 1);
        
         listBomb = [Select Id, Name, idProprietario__c From Bomba__c ];
        
        for(Bomba__c bAux : listBomb)
        {
            System.debug(bAux.idProprietario__c);
        }
        
         Test.stopTest();    
        }
        
    }
    
    
}